application: leobooksapp
version: 2
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /img
  static_dir: img

- url: /images
  script: admin.py

- url: /admin
  script: admin.py

- url: /admin/.*
  script: admin.py
  login: admin

- url: /
  script: main.py

- url: /edit/.*
  script: book.py

- url: /.*
  script: book.py
