application: leobooksapp
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /admin
  script: admin.py

- url: /admin/.*
  script: admin.py
  login: admin

- url: /.*
  script: main.py
